### ISSUE TITLE
what is defintion of alphabet

### ISSUE THREAD

**Issue by gobigrassland** [corticph/prefix-beam-search#2]
in function greedy_decoder, alphabet = list(ascii_lowercase) + [' ', '>']. But in function prefix_beam_search, alphabet = list(ascii_lowercase) + [' ', '>', '%']. i feel confused.

**Comment by csukuangfj** [comment]
@gobigrassland 

From https://medium.com/corti-ai/ctc-networks-and-language-models-prefix-beam-search-explained-c11d1ee23306

>our alphabet contains at least the letters A-Z, a space (_), and a blank token (-), where the latter is required by CTC networks. We will also be using an end-character (>) to be predicted after the last word.

In reality, it is up to you to define your alphabet depending on the actual application.

**Comment by gobigrassland** [comment]
@csukuangfj 
Thank you very much for your reply.
